[package]
name = "lunatic-wasi-api"
version = "0.14.0"
edition = "2021"
description = "Lunatic host functions for WASI."
homepage = "https://lunatic.solutions"
repository = "https://github.com/lunatic-solutions/lunatic/tree/main/crates/lunatic-wasi-api"
license = "Apache-2.0 OR MIT"

[dependencies]
lunatic-common-api = { workspace = true }
lunatic-error-api = { workspace = true }
lunatic-process = { workspace = true }
lunatic-stdout-capture = { workspace = true }

anyhow = { workspace = true }
async-trait = "0.1"
wasmtime = { workspace = true }
wasi-common = { workspace = true }
wiggle = "46.0.1"

[target.'cfg(unix)'.dependencies]
rustix = "1.1"

[target.'cfg(windows)'.dependencies]
io-extras = "0.18"

[dev-dependencies]
serde_json = "1.0.89"
tokio = { workspace = true, features = ["macros", "rt"] }
