[package]
name = "lunatic-control-axum"
version = "0.14.0"
edition = "2021"
description = "TBD"
homepage = "https://lunatic.solutions"
repository = "https://github.com/lunatic-solutions/lunatic/tree/main/crates"
license = "Apache-2.0 OR MIT"

[dependencies]
lunatic-control = { workspace = true }
lunatic-distributed = { workspace = true }

anyhow = { workspace = true }
axum = { version = "0.6", features = ["json", "query", "macros"] }
tower-http = { version = "0.3.0", features = ["limit"] }
chrono = { version = "0.4.23", default-features = false, features = ["clock", "std"] }
dashmap = { workspace = true }
http = "0.2.8"
log = { workspace = true }
rcgen = { workspace = true }
asn1-rs = { workspace = true }
serde = { workspace = true }
serde_json = "1.0.89"
sha2 = { workspace = true }
subtle = { workspace = true }
tokio = { workspace = true, features = ["io-util", "rt", "sync", "time", "fs"] }
uuid = { workspace = true }
zeroize = { workspace = true }
