;; This file is used for testing import signatures.

(module
    (import "lunatic::distributed" "copy_lookup_nodes_results" (func (param i64 i32 i32 i32) (result i32)))
    (import "lunatic::distributed" "default_server_certificates" (func (param i32 i32 i32 i32 i32) (result i32)))
    (import "lunatic::distributed" "exec_lookup_nodes" (func (param i32 i32 i32 i32 i32) (result i32)))
    (import "lunatic::distributed" "get_nodes" (func (param i32 i32) (result i32)))
    (import "lunatic::distributed" "module_id" (func (result i64)))
    (import "lunatic::distributed" "node_id" (func (result i64)))
    (import "lunatic::distributed" "nodes_count" (func (result i32)))
    (import "lunatic::distributed" "send" (func (param i64 i64) (result i32)))
    (import "lunatic::distributed" "send_receive_skip_search" (func (param i64 i64 i64 i64) (result i32)))
    (import "lunatic::distributed" "sign_node" (func (param i32 i32 i32 i32 i32 i32 i32) (result i32)))
    (import "lunatic::distributed" "sign_node_for_id" (func (param i32 i32 i32 i32 i32 i32 i32 i32 i64 i32) (result i32)))
    (import "lunatic::distributed" "sign_node_for_name" (func (param i32 i32 i32 i32 i32 i32 i32 i32 i32) (result i32)))
    (import "lunatic::distributed" "spawn" (func (param i64 i64 i64 i32 i32 i32 i32 i32) (result i32)))
    (import "lunatic::distributed" "test_root_cert" (func (param i32) (result i32)))

    (import "lunatic::error" "drop" (func (param i64)))
    (import "lunatic::error" "string_size" (func (param i64) (result i32)))
    (import "lunatic::error" "to_string" (func (param i64 i32)))

    (import "lunatic::message" "create_data" (func (param i64 i64)))
    (import "lunatic::message" "data_size" (func (result i64)))
    (import "lunatic::message" "get_process_id" (func (result i64)))
    (import "lunatic::message" "get_tag" (func (result i64)))
    (import "lunatic::message" "push_module" (func (param i64) (result i64)))
    (import "lunatic::message" "push_tcp_stream" (func (param i64) (result i64)))
    (import "lunatic::message" "push_tls_stream" (func (param i64) (result i64)))
    (import "lunatic::message" "push_udp_socket" (func (param i64) (result i64)))
    (import "lunatic::message" "read_data" (func (param i32 i32) (result i32)))
    (import "lunatic::message" "receive" (func (param i32 i32 i64) (result i32)))
    (import "lunatic::message" "seek_data" (func (param i64)))
    (import "lunatic::message" "send" (func (param i64) (result i32)))
    (import "lunatic::message" "send_receive_skip_search" (func (param i64 i64 i64) (result i32)))
    (import "lunatic::message" "take_module" (func (param i64) (result i64)))
    (import "lunatic::message" "take_tcp_stream" (func (param i64) (result i64)))
    (import "lunatic::message" "take_tls_stream" (func (param i64) (result i64)))
    (import "lunatic::message" "take_udp_socket" (func (param i64) (result i64)))
    (import "lunatic::message" "write_data" (func (param i32 i32) (result i32)))

    (import "lunatic::metrics" "counter" (func (param i32 i32 i64)))
    (import "lunatic::metrics" "decrement_gauge" (func (param i32 i32 f64)))
    (import "lunatic::metrics" "gauge" (func (param i32 i32 f64)))
    (import "lunatic::metrics" "histogram" (func (param i32 i32 f64)))
    (import "lunatic::metrics" "increment_counter" (func (param i32 i32)))
    (import "lunatic::metrics" "increment_gauge" (func (param i32 i32 f64)))

    (import "lunatic::networking" "clone_tcp_stream" (func (param i64) (result i64)))
    (import "lunatic::networking" "clone_tls_stream" (func (param i64) (result i64)))
    (import "lunatic::networking" "clone_udp_socket" (func (param i64) (result i64)))
    (import "lunatic::networking" "drop_dns_iterator" (func (param i64)))
    (import "lunatic::networking" "drop_tcp_listener" (func (param i64)))
    (import "lunatic::networking" "drop_tcp_stream" (func (param i64)))
    (import "lunatic::networking" "drop_tls_listener" (func (param i64)))
    (import "lunatic::networking" "drop_tls_stream" (func (param i64)))
    (import "lunatic::networking" "drop_udp_socket" (func (param i64)))
    (import "lunatic::networking" "get_peek_timeout" (func (param i64) (result i64)))
    (import "lunatic::networking" "get_read_timeout" (func (param i64) (result i64)))
    (import "lunatic::networking" "get_tls_read_timeout" (func (param i64) (result i64)))
    (import "lunatic::networking" "get_tls_write_timeout" (func (param i64) (result i64)))
    (import "lunatic::networking" "get_udp_socket_broadcast" (func (param i64) (result i32)))
    (import "lunatic::networking" "get_udp_socket_ttl" (func (param i64) (result i32)))
    (import "lunatic::networking" "get_write_timeout" (func (param i64) (result i64)))
    (import "lunatic::networking" "resolve" (func (param i32 i32 i64 i32) (result i32)))
    (import "lunatic::networking" "resolve_next" (func (param i64 i32 i32 i32 i32 i32) (result i32)))
    (import "lunatic::networking" "set_peek_timeout" (func (param i64 i64)))
    (import "lunatic::networking" "set_read_timeout" (func (param i64 i64)))
    (import "lunatic::networking" "set_tls_read_timeout" (func (param i64 i64)))
    (import "lunatic::networking" "set_tls_write_timeout" (func (param i64 i64)))
    (import "lunatic::networking" "set_udp_socket_broadcast" (func (param i64 i32)))
    (import "lunatic::networking" "set_udp_socket_ttl" (func (param i64 i32)))
    (import "lunatic::networking" "set_write_timeout" (func (param i64 i64)))
    (import "lunatic::networking" "tcp_accept" (func (param i64 i32 i32) (result i32)))
    (import "lunatic::networking" "tcp_bind" (func (param i32 i32 i32 i32 i32 i32) (result i32)))
    (import "lunatic::networking" "tcp_connect" (func (param i32 i32 i32 i32 i32 i64 i32) (result i32)))
    (import "lunatic::networking" "tcp_flush" (func (param i64 i32) (result i32)))
    (import "lunatic::networking" "tcp_local_addr" (func (param i64 i32) (result i32)))
    (import "lunatic::networking" "tcp_peek" (func (param i64 i32 i32 i32) (result i32)))
    (import "lunatic::networking" "tcp_peer_addr" (func (param i64 i32) (result i32)))
    (import "lunatic::networking" "tcp_read" (func (param i64 i32 i32 i32) (result i32)))
    (import "lunatic::networking" "tcp_write_vectored" (func (param i64 i32 i32 i32) (result i32)))
    (import "lunatic::networking" "tls_accept" (func (param i64 i32 i32) (result i32)))
    (import "lunatic::networking" "tls_bind" (func (param i32 i32 i32 i32 i32 i32 i32 i32 i32 i32) (result i32)))
    (import "lunatic::networking" "tls_bind_with_credential" (func (param i32 i32 i32 i32 i32 i32 i64 i64) (result i32)))
    (import "lunatic::networking" "tls_connect" (func (param i32 i32 i32 i64 i32 i32 i32) (result i32)))
    (import "lunatic::networking" "tls_flush" (func (param i64 i32) (result i32)))
    (import "lunatic::networking" "tls_local_addr" (func (param i64 i32) (result i32)))
    (import "lunatic::networking" "tls_read" (func (param i64 i32 i32 i32) (result i32)))
    (import "lunatic::networking" "tls_write_vectored" (func (param i64 i32 i32 i32) (result i32)))
    (import "lunatic::networking" "udp_bind" (func (param i32 i32 i32 i32 i32 i32) (result i32)))
    (import "lunatic::networking" "udp_connect" (func (param i64 i32 i32 i32 i32 i32 i64 i32) (result i32)))
    (import "lunatic::networking" "udp_local_addr" (func (param i64 i32) (result i32)))
    (import "lunatic::networking" "udp_peer_addr" (func (param i64 i32) (result i32)))
    (import "lunatic::networking" "udp_receive" (func (param i64 i32 i32 i32) (result i32)))
    (import "lunatic::networking" "udp_receive_from" (func (param i64 i32 i32 i32 i32) (result i32)))
    (import "lunatic::networking" "udp_send" (func (param i64 i32 i32 i32) (result i32)))
    (import "lunatic::networking" "udp_send_to" (func (param i64 i32 i32 i32 i32 i32 i32 i32 i32) (result i32)))

    (import "lunatic::process" "compile_module" (func (param i32 i32 i32) (result i32)))
    (import "lunatic::process" "config_can_compile_modules" (func (param i64) (result i32)))
    (import "lunatic::process" "config_can_create_configs" (func (param i64) (result i32)))
    (import "lunatic::process" "config_can_spawn_processes" (func (param i64) (result i32)))
    (import "lunatic::process" "config_can_use_tls_credential_handles" (func (param i64) (result i32)))
    (import "lunatic::process" "config_get_max_config_bytes" (func (param i64) (result i64)))
    (import "lunatic::process" "config_get_max_config_entries" (func (param i64) (result i32)))
    (import "lunatic::process" "config_get_max_configs" (func (param i64) (result i32)))
    (import "lunatic::process" "config_get_max_file_descriptors" (func (param i64) (result i32)))
    (import "lunatic::process" "config_get_max_fuel" (func (param i64) (result i64)))
    (import "lunatic::process" "config_get_max_mailbox_messages" (func (param i64) (result i32)))
    (import "lunatic::process" "config_get_max_memory" (func (param i64) (result i64)))
    (import "lunatic::process" "config_get_max_message_resources" (func (param i64) (result i32)))
    (import "lunatic::process" "config_get_max_message_size" (func (param i64) (result i64)))
    (import "lunatic::process" "config_get_max_module_bytes" (func (param i64) (result i64)))
    (import "lunatic::process" "config_get_max_modules" (func (param i64) (result i32)))
    (import "lunatic::process" "config_get_max_network_connections" (func (param i64) (result i32)))
    (import "lunatic::process" "config_get_max_signal_queue" (func (param i64) (result i32)))
    (import "lunatic::process" "config_get_max_sqlite_connections" (func (param i64) (result i32)))
    (import "lunatic::process" "config_get_max_sqlite_statements" (func (param i64) (result i32)))
    (import "lunatic::process" "config_get_max_table_elements" (func (param i64) (result i32)))
    (import "lunatic::process" "config_set_can_compile_modules" (func (param i64 i32)))
    (import "lunatic::process" "config_set_can_create_configs" (func (param i64 i32)))
    (import "lunatic::process" "config_set_can_spawn_processes" (func (param i64 i32)))
    (import "lunatic::process" "config_set_can_use_tls_credential_handles" (func (param i64 i32)))
    (import "lunatic::process" "config_set_checked" (func (param i64 i32 i64) (result i64)))
    (import "lunatic::process" "config_set_max_config_bytes" (func (param i64 i64)))
    (import "lunatic::process" "config_set_max_config_entries" (func (param i64 i32)))
    (import "lunatic::process" "config_set_max_configs" (func (param i64 i32)))
    (import "lunatic::process" "config_set_max_file_descriptors" (func (param i64 i32)))
    (import "lunatic::process" "config_set_max_fuel" (func (param i64 i64)))
    (import "lunatic::process" "config_set_max_mailbox_messages" (func (param i64 i32)))
    (import "lunatic::process" "config_set_max_memory" (func (param i64 i64)))
    (import "lunatic::process" "config_set_max_message_resources" (func (param i64 i32)))
    (import "lunatic::process" "config_set_max_message_size" (func (param i64 i64)))
    (import "lunatic::process" "config_set_max_module_bytes" (func (param i64 i64)))
    (import "lunatic::process" "config_set_max_modules" (func (param i64 i32)))
    (import "lunatic::process" "config_set_max_network_connections" (func (param i64 i32)))
    (import "lunatic::process" "config_set_max_signal_queue" (func (param i64 i32)))
    (import "lunatic::process" "config_set_max_sqlite_connections" (func (param i64 i32)))
    (import "lunatic::process" "config_set_max_sqlite_statements" (func (param i64 i32)))
    (import "lunatic::process" "config_set_max_table_elements" (func (param i64 i32)))
    (import "lunatic::process" "create_config" (func (result i64)))
    (import "lunatic::process" "die_when_link_dies" (func (param i32)))
    (import "lunatic::process" "drop_config" (func (param i64)))
    (import "lunatic::process" "drop_module" (func (param i64)))
    (import "lunatic::process" "environment_id" (func (result i64)))
    (import "lunatic::process" "exists" (func (param i64) (result i32)))
    (import "lunatic::process" "get_or_spawn" (func (param i32 i32 i64 i64 i64 i32 i32 i32 i32 i32 i32) (result i32)))
    (import "lunatic::process" "kill" (func (param i64)))
    (import "lunatic::process" "link" (func (param i64 i64)))
    (import "lunatic::process" "monitor" (func (param i64)))
    (import "lunatic::process" "process_id" (func (result i64)))
    (import "lunatic::process" "sleep_ms" (func (param i64)))
    (import "lunatic::process" "spawn" (func (param i64 i64 i64 i32 i32 i32 i32 i32) (result i32)))
    (import "lunatic::process" "stop_monitoring" (func (param i64)))
    (import "lunatic::process" "unlink" (func (param i64)))

    (import "lunatic::registry" "get" (func (param i32 i32 i32 i32) (result i32)))
    (import "lunatic::registry" "put" (func (param i32 i32 i64 i64)))
    (import "lunatic::registry" "remove" (func (param i32 i32)))

    (import "lunatic::sqlite" "bind_value" (func (param i64 i32 i32)))
    (import "lunatic::sqlite" "column_count" (func (param i64) (result i32)))
    (import "lunatic::sqlite" "column_name" (func (param i64 i32 i32) (result i32)))
    (import "lunatic::sqlite" "column_names" (func (param i64 i32) (result i32)))
    (import "lunatic::sqlite" "execute" (func (param i64 i32 i32) (result i32)))
    (import "lunatic::sqlite" "last_error" (func (param i64 i32) (result i32)))
    (import "lunatic::sqlite" "open" (func (param i32 i32 i32) (result i64)))
    (import "lunatic::sqlite" "query_prepare" (func (param i64 i32 i32) (result i64)))
    (import "lunatic::sqlite" "query_prepare_checked" (func (param i64 i32 i32 i32) (result i64)))
    (import "lunatic::sqlite" "read_column" (func (param i64 i32 i32) (result i32)))
    (import "lunatic::sqlite" "read_row" (func (param i64 i32) (result i32)))
    (import "lunatic::sqlite" "sqlite3_changes" (func (param i64) (result i32)))
    (import "lunatic::sqlite" "sqlite3_close" (func (param i64)))
    (import "lunatic::sqlite" "sqlite3_finalize" (func (param i64)))
    (import "lunatic::sqlite" "sqlite3_step" (func (param i64) (result i32)))
    (import "lunatic::sqlite" "statement_reset" (func (param i64)))

    (import "lunatic::timer" "cancel_timer" (func (param i64) (result i32)))
    (import "lunatic::timer" "send_after" (func (param i64 i64) (result i64)))

    (import "lunatic::trap" "catch" (func (param i32 i32) (result i32)))

    (import "lunatic::version" "major" (func (result i32)))
    (import "lunatic::version" "minor" (func (result i32)))
    (import "lunatic::version" "patch" (func (result i32)))

    (import "lunatic::wasi" "config_add_command_line_argument" (func (param i64 i32 i32)))
    (import "lunatic::wasi" "config_add_environment_variable" (func (param i64 i32 i32 i32 i32)))
    (import "lunatic::wasi" "config_preopen_dir" (func (param i64 i32 i32)))
    (import "lunatic::wasi" "config_preopen_dir_checked" (func (param i64 i32 i32) (result i64)))

    (import "wasi_snapshot_preview1" "args_get" (func (param i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "args_sizes_get" (func (param i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "clock_res_get" (func (param i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "clock_time_get" (func (param i32 i64 i32) (result i32)))
    (import "wasi_snapshot_preview1" "environ_get" (func (param i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "environ_sizes_get" (func (param i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "fd_advise" (func (param i32 i64 i64 i32) (result i32)))
    (import "wasi_snapshot_preview1" "fd_allocate" (func (param i32 i64 i64) (result i32)))
    (import "wasi_snapshot_preview1" "fd_close" (func (param i32) (result i32)))
    (import "wasi_snapshot_preview1" "fd_datasync" (func (param i32) (result i32)))
    (import "wasi_snapshot_preview1" "fd_fdstat_get" (func (param i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "fd_fdstat_set_flags" (func (param i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "fd_fdstat_set_rights" (func (param i32 i64 i64) (result i32)))
    (import "wasi_snapshot_preview1" "fd_filestat_get" (func (param i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "fd_filestat_set_size" (func (param i32 i64) (result i32)))
    (import "wasi_snapshot_preview1" "fd_filestat_set_times" (func (param i32 i64 i64 i32) (result i32)))
    (import "wasi_snapshot_preview1" "fd_pread" (func (param i32 i32 i32 i64 i32) (result i32)))
    (import "wasi_snapshot_preview1" "fd_prestat_dir_name" (func (param i32 i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "fd_prestat_get" (func (param i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "fd_pwrite" (func (param i32 i32 i32 i64 i32) (result i32)))
    (import "wasi_snapshot_preview1" "fd_read" (func (param i32 i32 i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "fd_readdir" (func (param i32 i32 i32 i64 i32) (result i32)))
    (import "wasi_snapshot_preview1" "fd_renumber" (func (param i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "fd_seek" (func (param i32 i64 i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "fd_sync" (func (param i32) (result i32)))
    (import "wasi_snapshot_preview1" "fd_tell" (func (param i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "fd_write" (func (param i32 i32 i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "path_create_directory" (func (param i32 i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "path_filestat_get" (func (param i32 i32 i32 i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "path_filestat_set_times" (func (param i32 i32 i32 i32 i64 i64 i32) (result i32)))
    (import "wasi_snapshot_preview1" "path_link" (func (param i32 i32 i32 i32 i32 i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "path_open" (func (param i32 i32 i32 i32 i32 i64 i64 i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "path_readlink" (func (param i32 i32 i32 i32 i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "path_remove_directory" (func (param i32 i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "path_rename" (func (param i32 i32 i32 i32 i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "path_symlink" (func (param i32 i32 i32 i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "path_unlink_file" (func (param i32 i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "poll_oneoff" (func (param i32 i32 i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "proc_exit" (func (param i32)))
    (import "wasi_snapshot_preview1" "proc_raise" (func (param i32) (result i32)))
    (import "wasi_snapshot_preview1" "random_get" (func (param i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "sched_yield" (func (result i32)))
    (import "wasi_snapshot_preview1" "sock_accept" (func (param i32 i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "sock_recv" (func (param i32 i32 i32 i32 i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "sock_send" (func (param i32 i32 i32 i32 i32) (result i32)))
    (import "wasi_snapshot_preview1" "sock_shutdown" (func (param i32 i32) (result i32)))

    (import "wasi_unstable" "args_get" (func (param i32 i32) (result i32)))
    (import "wasi_unstable" "args_sizes_get" (func (param i32 i32) (result i32)))
    (import "wasi_unstable" "clock_res_get" (func (param i32 i32) (result i32)))
    (import "wasi_unstable" "clock_time_get" (func (param i32 i64 i32) (result i32)))
    (import "wasi_unstable" "environ_get" (func (param i32 i32) (result i32)))
    (import "wasi_unstable" "environ_sizes_get" (func (param i32 i32) (result i32)))
    (import "wasi_unstable" "fd_advise" (func (param i32 i64 i64 i32) (result i32)))
    (import "wasi_unstable" "fd_allocate" (func (param i32 i64 i64) (result i32)))
    (import "wasi_unstable" "fd_close" (func (param i32) (result i32)))
    (import "wasi_unstable" "fd_datasync" (func (param i32) (result i32)))
    (import "wasi_unstable" "fd_fdstat_get" (func (param i32 i32) (result i32)))
    (import "wasi_unstable" "fd_fdstat_set_flags" (func (param i32 i32) (result i32)))
    (import "wasi_unstable" "fd_fdstat_set_rights" (func (param i32 i64 i64) (result i32)))
    (import "wasi_unstable" "fd_filestat_get" (func (param i32 i32) (result i32)))
    (import "wasi_unstable" "fd_filestat_set_size" (func (param i32 i64) (result i32)))
    (import "wasi_unstable" "fd_filestat_set_times" (func (param i32 i64 i64 i32) (result i32)))
    (import "wasi_unstable" "fd_pread" (func (param i32 i32 i32 i64 i32) (result i32)))
    (import "wasi_unstable" "fd_prestat_dir_name" (func (param i32 i32 i32) (result i32)))
    (import "wasi_unstable" "fd_prestat_get" (func (param i32 i32) (result i32)))
    (import "wasi_unstable" "fd_pwrite" (func (param i32 i32 i32 i64 i32) (result i32)))
    (import "wasi_unstable" "fd_read" (func (param i32 i32 i32 i32) (result i32)))
    (import "wasi_unstable" "fd_readdir" (func (param i32 i32 i32 i64 i32) (result i32)))
    (import "wasi_unstable" "fd_renumber" (func (param i32 i32) (result i32)))
    (import "wasi_unstable" "fd_seek" (func (param i32 i64 i32 i32) (result i32)))
    (import "wasi_unstable" "fd_sync" (func (param i32) (result i32)))
    (import "wasi_unstable" "fd_tell" (func (param i32 i32) (result i32)))
    (import "wasi_unstable" "fd_write" (func (param i32 i32 i32 i32) (result i32)))
    (import "wasi_unstable" "path_create_directory" (func (param i32 i32 i32) (result i32)))
    (import "wasi_unstable" "path_filestat_get" (func (param i32 i32 i32 i32 i32) (result i32)))
    (import "wasi_unstable" "path_filestat_set_times" (func (param i32 i32 i32 i32 i64 i64 i32) (result i32)))
    (import "wasi_unstable" "path_link" (func (param i32 i32 i32 i32 i32 i32 i32) (result i32)))
    (import "wasi_unstable" "path_open" (func (param i32 i32 i32 i32 i32 i64 i64 i32 i32) (result i32)))
    (import "wasi_unstable" "path_readlink" (func (param i32 i32 i32 i32 i32 i32) (result i32)))
    (import "wasi_unstable" "path_remove_directory" (func (param i32 i32 i32) (result i32)))
    (import "wasi_unstable" "path_rename" (func (param i32 i32 i32 i32 i32 i32) (result i32)))
    (import "wasi_unstable" "path_symlink" (func (param i32 i32 i32 i32 i32) (result i32)))
    (import "wasi_unstable" "path_unlink_file" (func (param i32 i32 i32) (result i32)))
    (import "wasi_unstable" "poll_oneoff" (func (param i32 i32 i32 i32) (result i32)))
    (import "wasi_unstable" "proc_exit" (func (param i32)))
    (import "wasi_unstable" "proc_raise" (func (param i32) (result i32)))
    (import "wasi_unstable" "random_get" (func (param i32 i32) (result i32)))
    (import "wasi_unstable" "sched_yield" (func (result i32)))
    (import "wasi_unstable" "sock_recv" (func (param i32 i32 i32 i32 i32 i32) (result i32)))
    (import "wasi_unstable" "sock_send" (func (param i32 i32 i32 i32 i32) (result i32)))
    (import "wasi_unstable" "sock_shutdown" (func (param i32 i32) (result i32)))
)
