[package]
name = "embedded-v3-lunatic"
version = "0.1.0"
edition = "2018"
publish = false

[workspace]

[dependencies]
anyhow = { version = "=1.0.100", default-features = false, features = ["std"] }
lunatic-process = { path = "../../../../crates/lunatic-process", version = "=0.14.0", default-features = false }
serde = { version = "=1.0.229", default-features = false, features = ["derive", "std"] }
serde_json = { version = "=1.0.151", default-features = false, features = ["std"] }
sha2 = { version = "=0.10.9", default-features = false, features = ["std"] }
tokio = { version = "=1.53.1", default-features = false, features = ["macros", "rt-multi-thread", "sync", "time"] }
wasmtime = { version = "=46.0.1", default-features = false }
